name: Calculate Supported Distros
description: |
  Calculate supported distros and their corresponding codenames from
  all the folders and subfolders of voulge/stage/unstable.

outputs:
  includes:
    description: "List of matrix include items"
    value: ${{ steps.matrix-builder.outputs.includes }}

runs:
  using: composite
  steps:
    - name: Init Voulage
      shell: bash
      run: git clone --quiet --no-tags --branch main https://github.com/regolith-linux/voulage.git /tmp/voulage-stage-tool

    # - name: Init Voulage
    #   shell: bash
    #   run: |
    #     if [ ! -d /tmp/voulage-stage-tool ]; then
    #       git clone --quiet --no-tags --branch main https://github.com/regolith-linux/voulage.git /tmp/voulage-stage-tool
    #     else
    #       pushd /tmp/voulage-stage-tool >/dev/null
    #       git fetch
    #       git checkout --quiet main
    #       popd >/dev/null
    #     fi

    - name: Matrix Includes Builder
      id: matrix-builder
      shell: bash
      run: |
        INCLUDES=()

        for dir in /tmp/voulage-stage-tool/stage/unstable/*/*/; do
          distro=$(echo $dir | cut -d/ -f6)
          codename=$(echo $dir | cut -d/ -f7)

          INCLUDES+=($(jq -n -c --arg distro "$distro" --arg codename "$codename" '$ARGS.named'))
        done

        echo "includes=$(jq -n -c "[$(printf '%s\n' "${INCLUDES[@]}" | paste -sd,)]" '$ARGS.named')" >> $GITHUB_OUTPUT
