name: Promote Stage
run-name: Promote Stage ${{ inputs.stage-id }} to tag ${{ inputs.base-tag-name }} (${{ inputs.dry-run-mode }})

on:
  workflow_dispatch:
    inputs:
      stage-id:
        description: 'Stage to promote from (eg "unstable")'
        required: true
        default: unstable
      base-tag-name:
        description: 'Base tag name (eg "r3_2-beta2")'
        required: true
      package-name:
        description: 'Package Name Filter (inclusive, optional)'
      dry-run-mode:
        type: choice
        description: 'Mode'
        options:
          - dry-run
          - push-tags

jobs:
  promote:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Promote Stage
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets. GITHUB_TOKEN }}
        run: |
          set -x

          if [ "${{ inputs.dry-run-mode }}" == "push-tags" ]; then
            ${{ github.workspace }}/.github/scripts/tag-stage.sh \
              ${{ github.workspace }} \
              ${{ inputs.stage-id }} \
              ${{ inputs.base-tag-name }} \
              ${{ inputs.package-name }}
          else
            ${{ github.workspace }}/.github/scripts/tag-stage.sh \
              ${{ github.workspace }} \
              ${{ inputs.stage-id }} \
              ${{ inputs.base-tag-name }} \
              ${{ inputs.package-name }} \
              dry-run
          fi
