name: Promote Stage

on:
  workflow_dispatch:
    inputs:
      stage-id:
        description: 'Stage to promote from (eg "unstable")'
        required: true
        default: unstable
      base-tag-name:
        description: 'Base tag name (eg "r3_2-beta2")'
        required: true
      package-name:
        description: 'Package Name Filter (inclusive, optional)'
      dry-run-mode:
        type: choice
        description: 'Mode'
        options:
        - dry-run
        - push-tags

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Promote Stage
        id: build
        run: |
          set -x

          if [ "${{ github.event.inputs.dry-run-mode }}" == "push-tags" ]; then
            ${{ github.workspace }}/.github/scripts/tag-stage.sh \
              ${{ github.workspace }} \
              ${{ github.event.inputs.stage-id }} \
              ${{ github.event.inputs.base-tag-name }} \
              ${{ github.event.inputs.package-name }}
          else
            ${{ github.workspace }}/.github/scripts/tag-stage.sh \
              ${{ github.workspace }} \
              ${{ github.event.inputs.stage-id }} \
              ${{ github.event.inputs.base-tag-name }} \
              ${{ github.event.inputs.package-name }} \
              dry-run
          fi
