name: Rebuild Sources
run-name: Rebuild Sources ${{ inputs.only-distro }} ${{ inputs.only-codename }} ${{ inputs.only-component }} ${{ inputs.only-package }}

on:
  workflow_dispatch:
    inputs:
      pull-from:
        description: "Path on disk to pull from"
        required: true
        default: "/opt/archives/workspace/"
      push-to:
        description: "Path on disk to push to"
        required: true
        default: "/opt/archives/packages/"
      only-distro:
        description: "Only rebuild sources of this distro"
        required: false
        default: ""
      only-codename:
        description: "Only rebuild sources of this codename"
        required: false
        default: ""
      only-component:
        description: "Only rebuild sources of this component"
        required: false
        default: ""
      only-package:
        description: "Only rebuild sources of this package"
        required: false
        default: ""
  workflow_call:
    inputs:
      pull-from:
        description: "Path on disk to pull from"
        type: string
        required: true
        default: "/opt/archives/workspace/"
      push-to:
        description: "Path on disk to push to"
        type: string
        required: true
        default: "/opt/archives/packages/"
      only-distro:
        description: "Only rebuild sources of this distro"
        type: string
        required: false
        default: ""
      only-codename:
        description: "Only rebuild sources of this codename"
        type: string
        required: false
        default: ""
      only-component:
        description: "Only rebuild sources of this component"
        type: string
        required: false
        default: ""
      only-package:
        description: "Only rebuild sources of this package"
        type: string
        required: false
        default: ""

# Need to explicitly set shell according to: https://github.com/actions/runner/issues/353#issuecomment-1067227665
defaults:
  run:
    shell: bash

jobs:
  rebuild:
    runs-on: ubuntu-24.04
    container: "ghcr.io/regolith-linux/ci-ubuntu:noble-amd64"
    env:
      server-address: "${{ secrets.KAMATERA_HOSTNAME2 }}"
      server-username: "${{ secrets.KAMATERA_USERNAME }}"
    steps:
      - name: Import GPG Key
        uses: regolith-linux/actions/import-gpg@main
        with:
          gpg-key: "${{ secrets.PACKAGE_PRIVATE_KEY2 }}"

      - name: Setup SSH
        uses: regolith-linux/actions/setup-ssh@main
        with:
          ssh-host: "${{ env.server-address }}"
          ssh-key: "${{ secrets.KAMATERA_SSH_KEY }}"

      - name: Rebuild Sources
        uses: regolith-linux/actions/rebuild-sources@main
        with:
          pull-from-base: "${{ inputs.pull-from }}"
          push-to-base: "${{ inputs.push-to }}"
          workspace-subfolder: "voulage/"
          only-distro: "${{ inputs.only-distro }}"
          only-codename: "${{ inputs.only-codename }}"
          only-component: "${{ inputs.only-component }}"
          only-package: "${{ inputs.only-package }}"
