name: Test Regolith desktop is installable

on:
  workflow_dispatch:
  workflow_call:

jobs:
  debian-bookworm:
    runs-on: ${{ matrix.host-os }}
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing, stable, release-3_2]
        arch: [amd64, arm64]
        wm: [regolith-session-flashback]
        include:
          - arch: amd64
            host-os: ubuntu-20.04
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, bookworm]
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
          - stage: stable
            suite: stable
            component: main
          - stage: release-3_2
            suite: stable
            component: v3.2
    env:
      distro: debian
      codename: bookworm
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/debian/bookworm@main
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"
  
  debian-testing:
    runs-on: ${{ matrix.host-os }}
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing] # testing is never released
        arch: [amd64, arm64]
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - arch: amd64
            host-os: [self-hosted, Linux, X64, testing]
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, testing]
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
    env:
      distro: debian
      codename: testing
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/debian/testing@main
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"

  ubuntu-jammy:
    runs-on: ${{ matrix.host-os }}
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing, stable, release-3_0, release-3_1, release-3_2]
        arch: [amd64, arm64]
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - arch: amd64
            host-os: ubuntu-22.04
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, jammy]
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
          - stage: stable
            suite: stable
            component: main
          - stage: release-3_0
            suite: stable
            component: v3.0
          - stage: release-3_1
            suite: stable
            component: v3.1
          - stage: release-3_2
            suite: stable
            component: v3.2
        exclude:
          - stage: release-3_0
            wm: regolith-session-sway
    env:
      distro: ubuntu
      codename: jammy
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/ubuntu/jammy@main
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"

  ubuntu-noble:
    runs-on: ${{ matrix.host-os }}
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing, stable, release-3_2]
        arch: [amd64, arm64]
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - arch: amd64
            host-os: [self-hosted, Linux, X64, noble]
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, noble]
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
          - stage: stable
            suite: stable
            component: main
          - stage: release-3_2
            suite: stable
            component: v3.2
    env:
      distro: ubuntu
      codename: noble
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/ubuntu/noble@main
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"

  ubuntu-oracular:
    runs-on: ${{ matrix.host-os }}
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing]
        arch: [amd64, arm64]
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - arch: amd64
            host-os: [self-hosted, Linux, X64, oracular]
          - arch: arm64
            host-os: [self-hosted, Linux, ARM64, oracular]
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
    env:
      distro: ubuntu
      codename: oracular
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/ubuntu/oracular@main
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"
