name: Test Regolith Desktop
run-name: Test ${{ inputs.stage }} Regolith Desktop ${{ inputs.distro }} ${{ inputs.codename }} ${{ inputs.arch }}

on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Stages to test"
        type: choice
        options:
          - all
          - experimental
          - unstable
          - testing
          - stable
          - release-3_2
        required: true
        default: "all"
      distro:
        description: "Distro to test (debian, ubuntu)"
        type: choice
        options:
          - ""
          - debian
          - ubuntu
        required: false
        default: ""
      codename:
        description: "Codename to test (e.g. noble, bookworm)"
        type: string
        required: false
        default: ""
      arch:
        description: "Architecture to test (amd64, arm64)"
        type: choice
        options:
          - ""
          - amd64
          - arm64
        required: false
        default: ""
  workflow_call:
    inputs:
      stage:
        description: "Stage to test"
        type: string
        required: true
        default: "all"
      distro:
        description: "Distro to test (debian, ubuntu)"
        type: string
        required: false
        default: ""
      codename:
        description: "Codename to test (e.g. noble, bookworm)"
        type: string
        required: false
        default: ""
      arch:
        description: "Architecture to test (amd64, arm64)"
        type: string
        required: false
        default: ""

jobs:
  matrix-builder:
    runs-on: ubuntu-24.04
    outputs:
      arches: ${{ steps.calc-matrix.outputs.arches }}
      runner-arches: ${{ steps.calc-matrix.outputs.runner-arches }}
    steps:
      - name: Calculate Matrix
        id: calc-matrix
        run: |
          if [ -n "${{ inputs.arch }}" ]; then
            ARCHES=(${{ inputs.arch }})
          else
            ARCHES=(amd64 arm64)
          fi
          echo "arches=$(jq -n -c '$ARGS.positional' --args -- "${ARCHES[@]}")" >> $GITHUB_OUTPUT
          echo "runner-arches=$(jq -n -c "$(jq -n -c --arg amd64 "X64" --arg arm64 "arm64" '$ARGS.named')" '$ARGS.named')" >> $GITHUB_OUTPUT

  debian-bookworm:
    runs-on: [self-hosted, Linux, "${{ fromJSON(needs.matrix-builder.outputs.runner-arches)[matrix.arch] }}", bookworm] 
    needs: matrix-builder
    if: |
      (inputs.distro == '' && inputs.codename == '') ||
      (inputs.distro == 'debian' && inputs.codename == '') ||
      (inputs.distro == '' && inputs.codename == 'bookworm') ||
      (inputs.distro == 'debian' && inputs.codename == 'bookworm')
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing, stable, release-3_2]
        arch: ${{ fromJson(needs.matrix-builder.outputs.arches) }}
        wm: [regolith-session-flashback]
        include:
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
          - stage: stable
            suite: stable
            component: main
          - stage: release-3_2
            suite: stable
            component: v3.2
    env:
      distro: debian
      codename: bookworm
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/debian/bookworm@main
        if: inputs.stage == 'all' || inputs.stage == matrix.stage
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"
  
  debian-testing:
    runs-on: [self-hosted, Linux, "${{ fromJSON(needs.matrix-builder.outputs.runner-arches)[matrix.arch] }}", testing] 
    needs: matrix-builder
    if: |
      (inputs.distro == '' && inputs.codename == '') ||
      (inputs.distro == 'debian' && inputs.codename == '') ||
      (inputs.distro == '' && inputs.codename == 'testing') ||
      (inputs.distro == 'debian' && inputs.codename == 'testing')
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing] # testing is never released
        arch: ${{ fromJson(needs.matrix-builder.outputs.arches) }}
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
    env:
      distro: debian
      codename: testing
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/debian/testing@main
        if: inputs.stage == 'all' || inputs.stage == matrix.stage
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"

  ubuntu-jammy:
    runs-on: [self-hosted, Linux, "${{ fromJSON(needs.matrix-builder.outputs.runner-arches)[matrix.arch] }}", jammy] 
    needs: matrix-builder
    if: |
      (inputs.distro == '' && inputs.codename == '') ||
      (inputs.distro == 'ubuntu' && inputs.codename == '') ||
      (inputs.distro == '' && inputs.codename == 'jammy') ||
      (inputs.distro == 'ubuntu' && inputs.codename == 'jammy')
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing, stable, release-3_0, release-3_1, release-3_2]
        arch: ${{ fromJson(needs.matrix-builder.outputs.arches) }}
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
          - stage: stable
            suite: stable
            component: main
          - stage: release-3_0
            suite: stable
            component: v3.0
          - stage: release-3_1
            suite: stable
            component: v3.1
          - stage: release-3_2
            suite: stable
            component: v3.2
        exclude:
          - stage: release-3_0
            wm: regolith-session-sway
    env:
      distro: ubuntu
      codename: jammy
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/ubuntu/jammy@main
        if: inputs.stage == 'all' || inputs.stage == matrix.stage
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"

  ubuntu-noble:
    runs-on: [self-hosted, Linux, "${{ fromJSON(needs.matrix-builder.outputs.runner-arches)[matrix.arch] }}", noble] 
    needs: matrix-builder
    if: |
      (inputs.distro == '' && inputs.codename == '') ||
      (inputs.distro == 'ubuntu' && inputs.codename == '') ||
      (inputs.distro == '' && inputs.codename == 'noble') ||
      (inputs.distro == 'ubuntu' && inputs.codename == 'noble')
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing, stable, release-3_2]
        arch: ${{ fromJson(needs.matrix-builder.outputs.arches) }}
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
          - stage: stable
            suite: stable
            component: main
          - stage: release-3_2
            suite: stable
            component: v3.2
    env:
      distro: ubuntu
      codename: noble
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/ubuntu/noble@main
        if: inputs.stage == 'all' || inputs.stage == matrix.stage
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"

  ubuntu-oracular:
    runs-on: [self-hosted, Linux, "${{ fromJSON(needs.matrix-builder.outputs.runner-arches)[matrix.arch] }}", oracular] 
    needs: matrix-builder
    if: |
      (inputs.distro == '' && inputs.codename == '') ||
      (inputs.distro == 'ubuntu' && inputs.codename == '') ||
      (inputs.distro == '' && inputs.codename == 'oracular') ||
      (inputs.distro == 'ubuntu' && inputs.codename == 'oracular')
    strategy:
      fail-fast: false
      matrix:
        stage: [unstable, testing]
        arch: ${{ fromJson(needs.matrix-builder.outputs.arches) }}
        wm: [regolith-session-flashback, regolith-session-sway]
        include:
          - stage: unstable
            suite: unstable
            component: main
          - stage: testing
            suite: testing
            component: main
    env:
      distro: ubuntu
      codename: oracular
    steps:
      - name: Install ${{ matrix.wm }} ${{ matrix.stage }} on ${{ env.distro }} ${{ env.codename }}
        uses: regolith-linux/test-desktop-installable-action/ubuntu/oracular@main
        if: inputs.stage == 'all' || inputs.stage == matrix.stage
        with:
          apt-key-url: http://66.175.213.120/_regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] http://66.175.213.120/${{ env.distro }}/${{ matrix.suite }} ${{ env.codename }} ${{ matrix.component }}"
          target-package: "regolith-desktop ${{ matrix.wm }}"
